import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { IS_NOINDEX } from "@/lib/constans";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: !IS_NOINDEX,
    follow: !IS_NOINDEX,
    googleBot: {
      index: !IS_NOINDEX,
      follow: !IS_NOINDEX,
    },
  },
};

export const revalidate = 3600;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
